services:
  - type: web
    name: mashup-web
    env: python
    buildCommand: pip install -r MashupWeb/requirements.txt
    startCommand: gunicorn MashupWeb.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
